### ISSUE TITLE
Streaming fails on Rpi3

### ISSUE THREAD

**Issue by safepay** [aussieaddons/plugin.video.abc_iview#3077]
Hi,

Streaming is intermittent on my Rpi3 running the latest Libreelec and iView plugin.
Playback works for some videos on HD, but can then fail to play them if tried again.
Turning off HD and forcing SD seems to solve the problem.

Log file attached.

[kodi.log](https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/files/1339835/kodi.log)

Cheers.

**Comment by glennguy** [comment]
@safepay

Could you repeat the log file but turn on debug logging in settings>system
settings first? Also please enable component specific logging and in the
specify menu below it, enable FFMPEG logging. That should help us get to
the bottom of it. Thanks!

**Comment by glennguy** [comment]
@safepay also - how fast is your connection roughly? and how fast would it be right at the moment i.e http://speedtest.net ?

**Comment by safepay** [comment]
As requested!
[kodi.log](https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/files/1339988/kodi.log)

Speedtest.net reports a pretty decent connection at the moment: http://beta.speedtest.net/result/6662040833
(16.3 Mbps down)

Cheers.

**Comment by glennguy** [comment]
@safepay Ok I think I have it figured out.

So the technical explanation is that when Kodi is given a HLS m3u8 playlist like iView has, it will first download all of the available stream playlists (there's 6 of them ranging from 1024x576 down to audio only) and then from there download and decode the first chunk (around 10 seconds worth I think) of each stream to try and determine your connection speed and subsequently choose the right stream and start playback. The issue here is that either Kodi or FFMPEG has a timeout set (it would seem 30 seconds looking at the log) which has expired before playback has begun. Connection speed would play a factor here, but I think also processing speed of your system would hold it up a little too.

One possible solution for Kodi 15+:
Perhaps @andybotting can weigh in on whether we should include an option to force HQ (or the highest available quality) for playback, which would speed up the time it takes for the stream to start.

A solution for Kodi 17+:
In the settings for iView, enable inputstream.adaptive playback. Since you're on LibreELEC/17.4, I'm pretty sure the required components should already be on your system but if not, when you go to play a video it should prompt to install anything that is missing. Playback starts super quick too!
Give it a go and let us know how it is.

Cheers

Glenn

**Comment by safepay** [comment]
That is a very clear explanation!

I enable  inputstream.adaptive playback as suggested and reset the ability to play HD. The problem persists...

Same log file as before but with new bits at the bottom I hope.

[kodi.log](https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/files/1340240/kodi.log)

I can live with SD, but just like to help get these things right, particularly as RPi is a great little platform.

**Comment by glennguy** [comment]
I can't see any mention of inputstream.adaptive in the log, I think you may have pressed back instead of clicking OK when changing the settings - happens to me all the time 😄

**Comment by safepay** [comment]
Yes, I've done that a few times too, but not this time. Just checked and it was correctly set with both the sliders on (For HD and adaptive input stream).
Ironically, it is now working... go figure.
I'll see how this goes for a bit, and if it remains stable it provides a good fix. The alternative fix is just to turn off the HD, but this is less desirable of course.

**Comment by glennguy** [comment]
Please let us know if you're having any further issues.

You should be able to tell when inputstream.adaptive is being used. I just tested on my RPi3. I'm using the Estuary skin and with i.a off, once the screen dims after pressing OK it takes around 10 seconds before playback begins. With it on, about 1 or 2 seconds, so a big difference. From pressing OK it's the difference between 5 seconds and 15.

**Comment by safepay** [comment]
I realised that I did not have adaptive streaming installed, so fixed that...
[kodi.log](https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/files/1342363/kodi.log)

On the RPi3 it is very unstable - initially plays quickly, then pauses for about 15 seconds with a buffering circle, then gives stuttering playback.

I would suggest that the options are stick with SD or have some option to force a resolution as you previously suggested.

**Comment by glennguy** [comment]
I think the issue is your connection. Are you using wifi or wired for your
rpi3? You could do a rudimentary speedtest ssh'ing in to the RPI and wget a
remote file.

We could force the stream to hq for streaming without inputstream.adaptive
but you'd still get buffering.

On 29 Sep. 2017 07:17, "safepay" <notifications@github.com> wrote:

I realised that I did not have adaptive streaming installed, so fixed
that...
kodi.log
<https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/files/1342363/kodi.log>

On the RPi3 it is very unstable - initially plays quickly, then pauses for
about 15 seconds with a buffering circle, then gives stuttering playback.

I would suggest that the options are stick with SD or have some option to
force a resolution as you previously suggested.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview/issues/3077#issuecomment-332966554>,
or mute the thread
